// <auto-generated />
using System;
using Library.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.DAL.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20250812205154_seeding-data")]
    partial class seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("LocationInLibrary")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookID");

                    b.HasIndex("LocationID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "John Steinbeck",
                            Condition = 2,
                            Genre = 0,
                            ISBN = "9780140186390",
                            IsAvailable = true,
                            LocationID = 4,
                            LocationInLibrary = 101,
                            PublicationDate = new DateTime(1952, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "East of Eden"
                        },
                        new
                        {
                            BookID = 2,
                            Author = "Susanna Clarke",
                            Condition = 1,
                            Genre = 5,
                            ISBN = "9781526630810",
                            IsAvailable = false,
                            LocationID = 3,
                            LocationInLibrary = 102,
                            PublicationDate = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Piranesi"
                        },
                        new
                        {
                            BookID = 3,
                            Author = "Martha Wells",
                            Condition = 0,
                            Genre = 2,
                            ISBN = "9780765394866",
                            IsAvailable = false,
                            LocationID = 3,
                            LocationInLibrary = 103,
                            PublicationDate = new DateTime(2017, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "All Systems Red"
                        },
                        new
                        {
                            BookID = 4,
                            Author = "Mark Z. Danielewski",
                            Condition = 2,
                            Genre = 0,
                            ISBN = "9780375508325",
                            IsAvailable = true,
                            LocationID = 5,
                            LocationInLibrary = 104,
                            PublicationDate = new DateTime(2000, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "House of Leaves"
                        },
                        new
                        {
                            BookID = 5,
                            Author = "Brandon Sanderson",
                            Condition = 1,
                            Genre = 5,
                            ISBN = "9780765376671",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 105,
                            PublicationDate = new DateTime(2017, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oathbringer"
                        },
                        new
                        {
                            BookID = 6,
                            Author = "Eiichiro Oda",
                            Condition = 2,
                            Genre = 13,
                            ISBN = "9781423103349",
                            IsAvailable = false,
                            LocationID = 1,
                            LocationInLibrary = 106,
                            PublicationDate = new DateTime(1997, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "One Piece, Vol. 1: Romance Dawn"
                        },
                        new
                        {
                            BookID = 7,
                            Author = "John Steinbeck",
                            Condition = 2,
                            Genre = 0,
                            ISBN = "9780142000670",
                            IsAvailable = true,
                            LocationID = 4,
                            LocationInLibrary = 107,
                            PublicationDate = new DateTime(1939, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Grapes of Wrath"
                        },
                        new
                        {
                            BookID = 8,
                            Author = "John Steinbeck",
                            Condition = 2,
                            Genre = 0,
                            ISBN = "9780140177398",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 108,
                            PublicationDate = new DateTime(1937, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Of Mice and Men"
                        },
                        new
                        {
                            BookID = 9,
                            Author = "John Steinbeck",
                            Condition = 0,
                            Genre = 0,
                            ISBN = "9780143039631",
                            IsAvailable = false,
                            LocationID = 2,
                            LocationInLibrary = 109,
                            PublicationDate = new DateTime(1945, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cannery Row"
                        },
                        new
                        {
                            BookID = 10,
                            Author = "John Steinbeck",
                            Condition = 3,
                            Genre = 0,
                            ISBN = "9780140186420",
                            IsAvailable = true,
                            LocationID = 5,
                            LocationInLibrary = 110,
                            PublicationDate = new DateTime(1935, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tortilla Flat"
                        },
                        new
                        {
                            BookID = 11,
                            Author = "Susanna Clarke",
                            Condition = 1,
                            Genre = 5,
                            ISBN = "9781582344164",
                            IsAvailable = true,
                            LocationID = 3,
                            LocationInLibrary = 111,
                            PublicationDate = new DateTime(2004, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jonathan Strange & Mr Norrell"
                        },
                        new
                        {
                            BookID = 12,
                            Author = "Susanna Clarke",
                            Condition = 2,
                            Genre = 5,
                            ISBN = "9780747593119",
                            IsAvailable = false,
                            LocationID = 2,
                            LocationInLibrary = 112,
                            PublicationDate = new DateTime(2006, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Ladies of Grace Adieu"
                        },
                        new
                        {
                            BookID = 13,
                            Author = "Brandon Sanderson",
                            Condition = 1,
                            Genre = 5,
                            ISBN = "9780765316882",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 113,
                            PublicationDate = new DateTime(2010, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Way of Kings"
                        },
                        new
                        {
                            BookID = 14,
                            Author = "Brandon Sanderson",
                            Condition = 2,
                            Genre = 0,
                            ISBN = "9780765356352",
                            IsAvailable = true,
                            LocationID = 5,
                            LocationInLibrary = 114,
                            PublicationDate = new DateTime(2006, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mistborn: The Final Empire"
                        },
                        new
                        {
                            BookID = 15,
                            Author = "Brandon Sanderson",
                            Condition = 0,
                            Genre = 5,
                            ISBN = "9780765365279",
                            IsAvailable = false,
                            LocationID = 3,
                            LocationInLibrary = 115,
                            PublicationDate = new DateTime(2009, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Warbreaker"
                        },
                        new
                        {
                            BookID = 16,
                            Author = "George Orwell",
                            Condition = 2,
                            Genre = 0,
                            ISBN = "9780141185101",
                            IsAvailable = true,
                            LocationID = 4,
                            LocationInLibrary = 116,
                            PublicationDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984"
                        },
                        new
                        {
                            BookID = 17,
                            Author = "Harper Lee",
                            Condition = 1,
                            Genre = 0,
                            ISBN = "9780061120084",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 117,
                            PublicationDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookID = 18,
                            Author = "Jane Austen",
                            Condition = 2,
                            Genre = 0,
                            ISBN = "9780141439518",
                            IsAvailable = false,
                            LocationID = 5,
                            LocationInLibrary = 118,
                            PublicationDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            BookID = 19,
                            Author = "Yuval Noah Harari",
                            Condition = 1,
                            Genre = 1,
                            ISBN = "9780143127574",
                            IsAvailable = true,
                            LocationID = 3,
                            LocationInLibrary = 119,
                            PublicationDate = new DateTime(2014, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            BookID = 20,
                            Author = "Tara Westover",
                            Condition = 0,
                            Genre = 1,
                            ISBN = "9780679645573",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 120,
                            PublicationDate = new DateTime(2018, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Educated"
                        },
                        new
                        {
                            BookID = 21,
                            Author = "Michelle Obama",
                            Condition = 2,
                            Genre = 1,
                            ISBN = "9780385534246",
                            IsAvailable = false,
                            LocationID = 1,
                            LocationInLibrary = 121,
                            PublicationDate = new DateTime(2018, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Becoming"
                        },
                        new
                        {
                            BookID = 22,
                            Author = "Niccolò Machiavelli",
                            Condition = 3,
                            Genre = 1,
                            ISBN = "9780140449266",
                            IsAvailable = true,
                            LocationID = 4,
                            LocationInLibrary = 122,
                            PublicationDate = new DateTime(1532, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Prince"
                        },
                        new
                        {
                            BookID = 23,
                            Author = "Frank Herbert",
                            Condition = 2,
                            Genre = 2,
                            ISBN = "9780553293357",
                            IsAvailable = true,
                            LocationID = 3,
                            LocationInLibrary = 123,
                            PublicationDate = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dune"
                        },
                        new
                        {
                            BookID = 24,
                            Author = "Orson Scott Card",
                            Condition = 1,
                            Genre = 2,
                            ISBN = "9780345391803",
                            IsAvailable = true,
                            LocationID = 5,
                            LocationInLibrary = 124,
                            PublicationDate = new DateTime(1985, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ender's Game"
                        },
                        new
                        {
                            BookID = 25,
                            Author = "William Gibson",
                            Condition = 2,
                            Genre = 2,
                            ISBN = "9780441172719",
                            IsAvailable = false,
                            LocationID = 2,
                            LocationInLibrary = 125,
                            PublicationDate = new DateTime(1984, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Neuromancer"
                        },
                        new
                        {
                            BookID = 26,
                            Author = "Aldous Huxley",
                            Condition = 0,
                            Genre = 2,
                            ISBN = "9780060850524",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 126,
                            PublicationDate = new DateTime(1932, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Brave New World"
                        },
                        new
                        {
                            BookID = 27,
                            Author = "Agatha Christie",
                            Condition = 2,
                            Genre = 3,
                            ISBN = "9780446310789",
                            IsAvailable = true,
                            LocationID = 4,
                            LocationInLibrary = 127,
                            PublicationDate = new DateTime(1939, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            BookID = 28,
                            Author = "Stieg Larsson",
                            Condition = 1,
                            Genre = 3,
                            ISBN = "9780312971342",
                            IsAvailable = false,
                            LocationID = 3,
                            LocationInLibrary = 128,
                            PublicationDate = new DateTime(2005, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            BookID = 29,
                            Author = "Arthur Conan Doyle",
                            Condition = 2,
                            Genre = 3,
                            ISBN = "9780141192666",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 129,
                            PublicationDate = new DateTime(1902, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hound of the Baskervilles"
                        },
                        new
                        {
                            BookID = 30,
                            Author = "Gillian Flynn",
                            Condition = 0,
                            Genre = 3,
                            ISBN = "9780062073488",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 130,
                            PublicationDate = new DateTime(2012, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gone Girl"
                        },
                        new
                        {
                            BookID = 31,
                            Author = "Charlotte Brontë",
                            Condition = 2,
                            Genre = 4,
                            ISBN = "9780451524935",
                            IsAvailable = true,
                            LocationID = 5,
                            LocationInLibrary = 131,
                            PublicationDate = new DateTime(1847, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jane Eyre"
                        },
                        new
                        {
                            BookID = 32,
                            Author = "Emily Brontë",
                            Condition = 3,
                            Genre = 4,
                            ISBN = "9780143107729",
                            IsAvailable = true,
                            LocationID = 3,
                            LocationInLibrary = 132,
                            PublicationDate = new DateTime(1847, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            BookID = 33,
                            Author = "Jojo Moyes",
                            Condition = 1,
                            Genre = 4,
                            ISBN = "9780062358202",
                            IsAvailable = false,
                            LocationID = 4,
                            LocationInLibrary = 133,
                            PublicationDate = new DateTime(2012, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Me Before You"
                        },
                        new
                        {
                            BookID = 34,
                            Author = "John Green",
                            Condition = 2,
                            Genre = 4,
                            ISBN = "9780143125235",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 134,
                            PublicationDate = new DateTime(2012, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Fault in Our Stars"
                        },
                        new
                        {
                            BookID = 35,
                            Author = "J.R.R. Tolkien",
                            Condition = 2,
                            Genre = 5,
                            ISBN = "9780547928197",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 135,
                            PublicationDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BookID = 36,
                            Author = "George R.R. Martin",
                            Condition = 1,
                            Genre = 5,
                            ISBN = "9780553573404",
                            IsAvailable = true,
                            LocationID = 5,
                            LocationInLibrary = 136,
                            PublicationDate = new DateTime(1996, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            BookID = 37,
                            Author = "J.K. Rowling",
                            Condition = 1,
                            Genre = 6,
                            ISBN = "9780590353427",
                            IsAvailable = true,
                            LocationID = 3,
                            LocationInLibrary = 137,
                            PublicationDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            BookID = 38,
                            Author = "E.B. White",
                            Condition = 2,
                            Genre = 6,
                            ISBN = "9780064400558",
                            IsAvailable = true,
                            LocationID = 4,
                            LocationInLibrary = 138,
                            PublicationDate = new DateTime(1952, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Charlotte's Web"
                        },
                        new
                        {
                            BookID = 39,
                            Author = "Roald Dahl",
                            Condition = 0,
                            Genre = 6,
                            ISBN = "9780142402511",
                            IsAvailable = false,
                            LocationID = 2,
                            LocationInLibrary = 139,
                            PublicationDate = new DateTime(1988, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Matilda"
                        },
                        new
                        {
                            BookID = 40,
                            Author = "C.S. Lewis",
                            Condition = 2,
                            Genre = 6,
                            ISBN = "9780064404990",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 140,
                            PublicationDate = new DateTime(1950, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lion, the Witch and the Wardrobe"
                        },
                        new
                        {
                            BookID = 41,
                            Author = "Neil Gaiman & Terry Pratchett",
                            Condition = 1,
                            Genre = 7,
                            ISBN = "9780140287028",
                            IsAvailable = true,
                            LocationID = 5,
                            LocationInLibrary = 141,
                            PublicationDate = new DateTime(1990, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Good Omens"
                        },
                        new
                        {
                            BookID = 42,
                            Author = "Joseph Heller",
                            Condition = 2,
                            Genre = 7,
                            ISBN = "9780393355529",
                            IsAvailable = true,
                            LocationID = 3,
                            LocationInLibrary = 142,
                            PublicationDate = new DateTime(1961, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Catch-22"
                        },
                        new
                        {
                            BookID = 43,
                            Author = "Douglas Adams",
                            Condition = 0,
                            Genre = 7,
                            ISBN = "9780142437261",
                            IsAvailable = false,
                            LocationID = 4,
                            LocationInLibrary = 143,
                            PublicationDate = new DateTime(1979, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            BookID = 44,
                            Author = "Tina Fey",
                            Condition = 1,
                            Genre = 7,
                            ISBN = "9781594483295",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 144,
                            PublicationDate = new DateTime(2011, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bossypants"
                        },
                        new
                        {
                            BookID = 45,
                            Author = "Robert C. Martin",
                            Condition = 1,
                            Genre = 8,
                            ISBN = "9780596523022",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 145,
                            PublicationDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookID = 46,
                            Author = "Andrew Hunt & David Thomas",
                            Condition = 2,
                            Genre = 8,
                            ISBN = "9780135957059",
                            IsAvailable = true,
                            LocationID = 3,
                            LocationInLibrary = 146,
                            PublicationDate = new DateTime(1999, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookID = 47,
                            Author = "Martin Kleppmann",
                            Condition = 0,
                            Genre = 8,
                            ISBN = "9780134685991",
                            IsAvailable = false,
                            LocationID = 5,
                            LocationInLibrary = 147,
                            PublicationDate = new DateTime(2017, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Designing Data-Intensive Applications"
                        },
                        new
                        {
                            BookID = 48,
                            Author = "Niall Murphy",
                            Condition = 1,
                            Genre = 8,
                            ISBN = "9781492052203",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 148,
                            PublicationDate = new DateTime(2016, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Site Reliability Engineering"
                        },
                        new
                        {
                            BookID = 49,
                            Author = "Stephen Hawking",
                            Condition = 2,
                            Genre = 9,
                            ISBN = "9780393355628",
                            IsAvailable = true,
                            LocationID = 4,
                            LocationInLibrary = 149,
                            PublicationDate = new DateTime(1988, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            BookID = 50,
                            Author = "Richard Dawkins",
                            Condition = 1,
                            Genre = 9,
                            ISBN = "9780143111580",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 150,
                            PublicationDate = new DateTime(1976, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Selfish Gene"
                        },
                        new
                        {
                            BookID = 51,
                            Author = "Rebecca Skloot",
                            Condition = 2,
                            Genre = 9,
                            ISBN = "9780374533557",
                            IsAvailable = false,
                            LocationID = 3,
                            LocationInLibrary = 151,
                            PublicationDate = new DateTime(2010, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Immortal Life of Henrietta Lacks"
                        },
                        new
                        {
                            BookID = 52,
                            Author = "Carlo Rovelli",
                            Condition = 0,
                            Genre = 9,
                            ISBN = "9780141988511",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 152,
                            PublicationDate = new DateTime(2018, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Order of Time"
                        },
                        new
                        {
                            BookID = 53,
                            Author = "James Stewart",
                            Condition = 2,
                            Genre = 10,
                            ISBN = "9780131103627",
                            IsAvailable = true,
                            LocationID = 5,
                            LocationInLibrary = 153,
                            PublicationDate = new DateTime(2002, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Calculus: Early Transcendentals"
                        },
                        new
                        {
                            BookID = 54,
                            Author = "James Kurose",
                            Condition = 1,
                            Genre = 10,
                            ISBN = "9780134438986",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 154,
                            PublicationDate = new DateTime(2016, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Computer Networking: A Top-Down Approach"
                        },
                        new
                        {
                            BookID = 55,
                            Author = "Paula Yurkanis Bruice",
                            Condition = 2,
                            Genre = 10,
                            ISBN = "9780133594140",
                            IsAvailable = false,
                            LocationID = 3,
                            LocationInLibrary = 155,
                            PublicationDate = new DateTime(2013, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Organic Chemistry"
                        },
                        new
                        {
                            BookID = 56,
                            Author = "James W. Kalat",
                            Condition = 0,
                            Genre = 10,
                            ISBN = "9780134093413",
                            IsAvailable = true,
                            LocationID = 4,
                            LocationInLibrary = 156,
                            PublicationDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to Psychology"
                        },
                        new
                        {
                            BookID = 57,
                            Author = "Alan Moore",
                            Condition = 2,
                            Genre = 11,
                            ISBN = "9781401225759",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 157,
                            PublicationDate = new DateTime(1987, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Watchmen"
                        },
                        new
                        {
                            BookID = 58,
                            Author = "Alan Moore",
                            Condition = 1,
                            Genre = 11,
                            ISBN = "9781401238964",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 158,
                            PublicationDate = new DateTime(1989, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "V for Vendetta"
                        },
                        new
                        {
                            BookID = 59,
                            Author = "Brian K. Vaughan",
                            Condition = 0,
                            Genre = 11,
                            ISBN = "9780785190219",
                            IsAvailable = false,
                            LocationID = 5,
                            LocationInLibrary = 159,
                            PublicationDate = new DateTime(2012, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Saga, Vol. 1"
                        },
                        new
                        {
                            BookID = 60,
                            Author = "Art Spiegelman",
                            Condition = 2,
                            Genre = 11,
                            ISBN = "9781401248192",
                            IsAvailable = true,
                            LocationID = 3,
                            LocationInLibrary = 160,
                            PublicationDate = new DateTime(1986, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Maus I"
                        },
                        new
                        {
                            BookID = 61,
                            Author = "Various",
                            Condition = 1,
                            Genre = 12,
                            ISBN = "9770028088008",
                            IsAvailable = true,
                            LocationID = 4,
                            LocationInLibrary = 161,
                            PublicationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "National Geographic, Jan 2025"
                        },
                        new
                        {
                            BookID = 62,
                            Author = "Various",
                            Condition = 0,
                            Genre = 12,
                            ISBN = "9770028088015",
                            IsAvailable = true,
                            LocationID = 2,
                            LocationInLibrary = 162,
                            PublicationDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The New Yorker, Feb 2025"
                        },
                        new
                        {
                            BookID = 63,
                            Author = "Various",
                            Condition = 1,
                            Genre = 12,
                            ISBN = "9770028088022",
                            IsAvailable = false,
                            LocationID = 1,
                            LocationInLibrary = 163,
                            PublicationDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Scientific American, Mar 2025"
                        },
                        new
                        {
                            BookID = 64,
                            Author = "Various",
                            Condition = 2,
                            Genre = 12,
                            ISBN = "9770028088039",
                            IsAvailable = true,
                            LocationID = 3,
                            LocationInLibrary = 164,
                            PublicationDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Time, Apr 2025"
                        },
                        new
                        {
                            BookID = 65,
                            Author = "Masashi Kishimoto",
                            Condition = 2,
                            Genre = 13,
                            ISBN = "9781421501680",
                            IsAvailable = true,
                            LocationID = 1,
                            LocationInLibrary = 165,
                            PublicationDate = new DateTime(2003, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Naruto, Vol. 1"
                        },
                        new
                        {
                            BookID = 66,
                            Author = "Hajime Isayama",
                            Condition = 1,
                            Genre = 13,
                            ISBN = "9781421520544",
                            IsAvailable = true,
                            LocationID = 5,
                            LocationInLibrary = 166,
                            PublicationDate = new DateTime(2012, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Attack on Titan, Vol. 1"
                        },
                        new
                        {
                            BookID = 67,
                            Author = "Hiromu Arakawa",
                            Condition = 0,
                            Genre = 13,
                            ISBN = "9781591161783",
                            IsAvailable = false,
                            LocationID = 2,
                            LocationInLibrary = 167,
                            PublicationDate = new DateTime(2005, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fullmetal Alchemist, Vol. 1"
                        });
                });

            modelBuilder.Entity("Library.Models.Loan", b =>
                {
                    b.Property<int>("LoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBorrowed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanStatus")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LoanID");

                    b.HasIndex("BookID");

                    b.HasIndex("LocationID");

                    b.HasIndex("UserID");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanID = 1,
                            BookID = 2,
                            DateBorrowed = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 3,
                            UserID = 3
                        },
                        new
                        {
                            LoanID = 2,
                            BookID = 3,
                            DateBorrowed = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 2,
                            LocationID = 3,
                            UserID = 2
                        },
                        new
                        {
                            LoanID = 3,
                            BookID = 6,
                            DateBorrowed = new DateTime(2025, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 3,
                            LocationID = 1,
                            UserID = 1
                        },
                        new
                        {
                            LoanID = 4,
                            BookID = 11,
                            DateBorrowed = new DateTime(2025, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 3,
                            UserID = 3
                        },
                        new
                        {
                            LoanID = 5,
                            BookID = 15,
                            DateBorrowed = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 2,
                            LocationID = 3,
                            UserID = 3
                        },
                        new
                        {
                            LoanID = 6,
                            BookID = 12,
                            DateBorrowed = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 3,
                            LocationID = 2,
                            UserID = 3
                        },
                        new
                        {
                            LoanID = 7,
                            BookID = 16,
                            DateBorrowed = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 1,
                            LocationID = 4,
                            UserID = 3
                        },
                        new
                        {
                            LoanID = 8,
                            BookID = 19,
                            DateBorrowed = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 3,
                            UserID = 3
                        },
                        new
                        {
                            LoanID = 9,
                            BookID = 9,
                            DateBorrowed = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 2,
                            UserID = 12
                        },
                        new
                        {
                            LoanID = 10,
                            BookID = 25,
                            DateBorrowed = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 2,
                            LocationID = 2,
                            UserID = 12
                        },
                        new
                        {
                            LoanID = 11,
                            BookID = 23,
                            DateBorrowed = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 3,
                            UserID = 13
                        },
                        new
                        {
                            LoanID = 12,
                            BookID = 28,
                            DateBorrowed = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 3,
                            LocationID = 3,
                            UserID = 13
                        },
                        new
                        {
                            LoanID = 13,
                            BookID = 27,
                            DateBorrowed = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 1,
                            LocationID = 4,
                            UserID = 14
                        },
                        new
                        {
                            LoanID = 14,
                            BookID = 33,
                            DateBorrowed = new DateTime(2025, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 2,
                            LocationID = 4,
                            UserID = 14
                        },
                        new
                        {
                            LoanID = 15,
                            BookID = 37,
                            DateBorrowed = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 5,
                            UserID = 15
                        },
                        new
                        {
                            LoanID = 16,
                            BookID = 47,
                            DateBorrowed = new DateTime(2025, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 3,
                            LocationID = 5,
                            UserID = 15
                        },
                        new
                        {
                            LoanID = 17,
                            BookID = 35,
                            DateBorrowed = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 1,
                            LocationID = 1,
                            UserID = 16
                        },
                        new
                        {
                            LoanID = 18,
                            BookID = 45,
                            DateBorrowed = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 2,
                            LocationID = 1,
                            UserID = 16
                        },
                        new
                        {
                            LoanID = 19,
                            BookID = 39,
                            DateBorrowed = new DateTime(2025, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 2,
                            UserID = 17
                        },
                        new
                        {
                            LoanID = 20,
                            BookID = 57,
                            DateBorrowed = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 3,
                            LocationID = 2,
                            UserID = 17
                        },
                        new
                        {
                            LoanID = 21,
                            BookID = 51,
                            DateBorrowed = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 1,
                            LocationID = 3,
                            UserID = 18
                        },
                        new
                        {
                            LoanID = 22,
                            BookID = 55,
                            DateBorrowed = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 2,
                            LocationID = 3,
                            UserID = 18
                        },
                        new
                        {
                            LoanID = 23,
                            BookID = 43,
                            DateBorrowed = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 4,
                            UserID = 19
                        },
                        new
                        {
                            LoanID = 24,
                            BookID = 61,
                            DateBorrowed = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 3,
                            LocationID = 4,
                            UserID = 19
                        },
                        new
                        {
                            LoanID = 25,
                            BookID = 59,
                            DateBorrowed = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 1,
                            LocationID = 5,
                            UserID = 20
                        },
                        new
                        {
                            LoanID = 26,
                            BookID = 53,
                            DateBorrowed = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 2,
                            LocationID = 5,
                            UserID = 20
                        },
                        new
                        {
                            LoanID = 27,
                            BookID = 65,
                            DateBorrowed = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 1,
                            UserID = 21
                        },
                        new
                        {
                            LoanID = 28,
                            BookID = 63,
                            DateBorrowed = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 3,
                            LocationID = 1,
                            UserID = 21
                        },
                        new
                        {
                            LoanID = 29,
                            BookID = 67,
                            DateBorrowed = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 1,
                            LocationID = 2,
                            UserID = 22
                        },
                        new
                        {
                            LoanID = 30,
                            BookID = 20,
                            DateBorrowed = new DateTime(2025, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 2,
                            LocationID = 2,
                            UserID = 22
                        },
                        new
                        {
                            LoanID = 31,
                            BookID = 28,
                            DateBorrowed = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 3,
                            UserID = 23
                        },
                        new
                        {
                            LoanID = 32,
                            BookID = 19,
                            DateBorrowed = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 1,
                            LocationID = 3,
                            UserID = 23
                        },
                        new
                        {
                            LoanID = 33,
                            BookID = 49,
                            DateBorrowed = new DateTime(2025, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 4,
                            UserID = 24
                        },
                        new
                        {
                            LoanID = 34,
                            BookID = 27,
                            DateBorrowed = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 2,
                            LocationID = 4,
                            UserID = 24
                        },
                        new
                        {
                            LoanID = 35,
                            BookID = 41,
                            DateBorrowed = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 0,
                            LocationID = 5,
                            UserID = 25
                        },
                        new
                        {
                            LoanID = 36,
                            BookID = 33,
                            DateBorrowed = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanStatus = 3,
                            LocationID = 5,
                            UserID = 25
                        });
                });

            modelBuilder.Entity("Library.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LocationName")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationID = 1,
                            Address = "100 Boye-Ogundiya Way",
                            LocationName = 0,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            LocationID = 2,
                            Address = "200 Hall Street",
                            LocationName = 1,
                            PhoneNumber = "1234567891"
                        },
                        new
                        {
                            LocationID = 3,
                            Address = "300 Hua Avenue",
                            LocationName = 2,
                            PhoneNumber = "1234567892"
                        },
                        new
                        {
                            LocationID = 4,
                            Address = "400 Mitchell Road",
                            LocationName = 3,
                            PhoneNumber = "1234567893"
                        },
                        new
                        {
                            LocationID = 5,
                            Address = "500 Solomon Boulevard",
                            LocationName = 4,
                            PhoneNumber = "1234567894"
                        });
                });

            modelBuilder.Entity("Library.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("LocationID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Address = "100 Boye-Ogundiya Way",
                            Email = "admin1@library.com",
                            Gender = 3,
                            LocationID = 1,
                            Name = "Admin User1",
                            PhoneNumber = "1234567890",
                            Role = 0
                        },
                        new
                        {
                            UserID = 4,
                            Address = "200 Hall Street",
                            Email = "admin2@library.com",
                            Gender = 1,
                            LocationID = 2,
                            Name = "Admin User2",
                            PhoneNumber = "1234567891",
                            Role = 0
                        },
                        new
                        {
                            UserID = 5,
                            Address = "300 Hua Street",
                            Email = "admin3@library.com",
                            Gender = 0,
                            LocationID = 3,
                            Name = "Admin User3",
                            PhoneNumber = "1234567892",
                            Role = 0
                        },
                        new
                        {
                            UserID = 6,
                            Address = "400 Mitchell Road",
                            Email = "admin4@library.com",
                            Gender = 1,
                            LocationID = 4,
                            Name = "Admin User4",
                            PhoneNumber = "1234567893",
                            Role = 0
                        },
                        new
                        {
                            UserID = 7,
                            Address = "500 Solomon Boulevard",
                            Email = "admin5@library.com",
                            Gender = 1,
                            LocationID = 5,
                            Name = "Admin User5",
                            PhoneNumber = "1234567894",
                            Role = 0
                        },
                        new
                        {
                            UserID = 8,
                            Address = "100 Boye-Ogundiya Way",
                            Email = "staff1@library.com",
                            Gender = 1,
                            LocationID = 1,
                            Name = "Staff User",
                            PhoneNumber = "1234567890",
                            Role = 1
                        },
                        new
                        {
                            UserID = 2,
                            Address = "200 Hall Street",
                            Email = "staff2@library.com",
                            Gender = 1,
                            LocationID = 2,
                            Name = "Staff User",
                            PhoneNumber = "1234567891",
                            Role = 1
                        },
                        new
                        {
                            UserID = 9,
                            Address = "300 Hua Street",
                            Email = "staff3@library.com",
                            Gender = 0,
                            LocationID = 3,
                            Name = "Staff User",
                            PhoneNumber = "1234567892",
                            Role = 1
                        },
                        new
                        {
                            UserID = 10,
                            Address = "400 Mitchell Road",
                            Email = "staff4@library.com",
                            Gender = 3,
                            LocationID = 4,
                            Name = "Staff User",
                            PhoneNumber = "1234567893",
                            Role = 1
                        },
                        new
                        {
                            UserID = 11,
                            Address = "500 Solomon Boulevard",
                            Email = "staff5@library.com",
                            Gender = 0,
                            LocationID = 5,
                            Name = "Staff User",
                            PhoneNumber = "1234567894",
                            Role = 1
                        },
                        new
                        {
                            UserID = 3,
                            Address = "100 Boye-Ogundiya Way",
                            Email = "reader1@library.com",
                            Gender = 0,
                            LocationID = 1,
                            Name = "Reader User1",
                            PhoneNumber = "1111111111",
                            Role = 2
                        },
                        new
                        {
                            UserID = 12,
                            Address = "100 Boye-Ogundiya Way",
                            Email = "reader2@library.com",
                            Gender = 1,
                            LocationID = 1,
                            Name = "Reader User2",
                            PhoneNumber = "1111111112",
                            Role = 2
                        },
                        new
                        {
                            UserID = 13,
                            Address = "100 Boye-Ogundiya Way",
                            Email = "reader3@library.com",
                            Gender = 2,
                            LocationID = 1,
                            Name = "Reader User3",
                            PhoneNumber = "1111111113",
                            Role = 2
                        },
                        new
                        {
                            UserID = 14,
                            Address = "100 Boye-Ogundiya Way",
                            Email = "reader4@library.com",
                            Gender = 0,
                            LocationID = 1,
                            Name = "Reader User4",
                            PhoneNumber = "11111111114",
                            Role = 2
                        },
                        new
                        {
                            UserID = 15,
                            Address = "100 Boye-Ogundiya Way",
                            Email = "reader5@library.com",
                            Gender = 1,
                            LocationID = 1,
                            Name = "Reader User5",
                            PhoneNumber = "1111111115",
                            Role = 2
                        },
                        new
                        {
                            UserID = 16,
                            Address = "200 Hall Street",
                            Email = "reader6@library.com",
                            Gender = 0,
                            LocationID = 2,
                            Name = "Reader User6",
                            PhoneNumber = "1111111116",
                            Role = 2
                        },
                        new
                        {
                            UserID = 17,
                            Address = "200 Hall Street",
                            Email = "reader7@library.com",
                            Gender = 1,
                            LocationID = 2,
                            Name = "Reader User7",
                            PhoneNumber = "1111111117",
                            Role = 2
                        },
                        new
                        {
                            UserID = 18,
                            Address = "200 Hall Street",
                            Email = "reader8@library.com",
                            Gender = 2,
                            LocationID = 2,
                            Name = "Reader User8",
                            PhoneNumber = "1111111118",
                            Role = 2
                        },
                        new
                        {
                            UserID = 19,
                            Address = "200 Hall Street",
                            Email = "reader9@library.com",
                            Gender = 0,
                            LocationID = 2,
                            Name = "Reader User9",
                            PhoneNumber = "11111111119",
                            Role = 2
                        },
                        new
                        {
                            UserID = 20,
                            Address = "200 Hall Street",
                            Email = "reader10@library.com",
                            Gender = 1,
                            LocationID = 2,
                            Name = "Reader User10",
                            PhoneNumber = "1111111110",
                            Role = 2
                        },
                        new
                        {
                            UserID = 21,
                            Address = "300 Hua Street",
                            Email = "reader11@library.com",
                            Gender = 0,
                            LocationID = 3,
                            Name = "Reader User11",
                            PhoneNumber = "1111111121",
                            Role = 2
                        },
                        new
                        {
                            UserID = 22,
                            Address = "300 Hua Street",
                            Email = "reader12@library.com",
                            Gender = 1,
                            LocationID = 3,
                            Name = "Reader User12",
                            PhoneNumber = "1111111122",
                            Role = 2
                        },
                        new
                        {
                            UserID = 23,
                            Address = "300 Hua Street",
                            Email = "reader13@library.com",
                            Gender = 2,
                            LocationID = 3,
                            Name = "Reader User13",
                            PhoneNumber = "1111111123",
                            Role = 2
                        },
                        new
                        {
                            UserID = 24,
                            Address = "300 Hua Street",
                            Email = "reader14@library.com",
                            Gender = 0,
                            LocationID = 3,
                            Name = "Reader User14",
                            PhoneNumber = "11111111124",
                            Role = 2
                        },
                        new
                        {
                            UserID = 25,
                            Address = "300 Hua Street",
                            Email = "reader15@library.com",
                            Gender = 1,
                            LocationID = 3,
                            Name = "Reader User15",
                            PhoneNumber = "1111111125",
                            Role = 2
                        },
                        new
                        {
                            UserID = 26,
                            Address = "400 Mitchell Road",
                            Email = "reader16@library.com",
                            Gender = 0,
                            LocationID = 4,
                            Name = "Reader User16",
                            PhoneNumber = "1111111126",
                            Role = 2
                        },
                        new
                        {
                            UserID = 27,
                            Address = "400 Mitchell Road",
                            Email = "reader17@library.com",
                            Gender = 1,
                            LocationID = 4,
                            Name = "Reader User17",
                            PhoneNumber = "1111111127",
                            Role = 2
                        },
                        new
                        {
                            UserID = 28,
                            Address = "400 Mitchell Road",
                            Email = "reader18@library.com",
                            Gender = 2,
                            LocationID = 4,
                            Name = "Reader User18",
                            PhoneNumber = "1111111128",
                            Role = 2
                        },
                        new
                        {
                            UserID = 29,
                            Address = "400 Mitchell Road",
                            Email = "reader19@library.com",
                            Gender = 0,
                            LocationID = 4,
                            Name = "Reader User19",
                            PhoneNumber = "11111111129",
                            Role = 2
                        },
                        new
                        {
                            UserID = 30,
                            Address = "400 Mitchell Road",
                            Email = "reader20@library.com",
                            Gender = 1,
                            LocationID = 4,
                            Name = "Reader User20",
                            PhoneNumber = "1111111130",
                            Role = 2
                        },
                        new
                        {
                            UserID = 31,
                            Address = "500 Solomon Boulevard",
                            Email = "reader21@library.com",
                            Gender = 0,
                            LocationID = 5,
                            Name = "Reader User21",
                            PhoneNumber = "1111111131",
                            Role = 2
                        },
                        new
                        {
                            UserID = 32,
                            Address = "500 Solomon Boulevard",
                            Email = "reader22@library.com",
                            Gender = 1,
                            LocationID = 5,
                            Name = "Reader User22",
                            PhoneNumber = "1111111132",
                            Role = 2
                        },
                        new
                        {
                            UserID = 33,
                            Address = "500 Solomon Boulevard",
                            Email = "reader23@library.com",
                            Gender = 2,
                            LocationID = 5,
                            Name = "Reader User23",
                            PhoneNumber = "1111111133",
                            Role = 2
                        },
                        new
                        {
                            UserID = 34,
                            Address = "500 Solomon Boulevard",
                            Email = "reader24@library.com",
                            Gender = 0,
                            LocationID = 5,
                            Name = "Reader User24",
                            PhoneNumber = "11111111134",
                            Role = 2
                        },
                        new
                        {
                            UserID = 35,
                            Address = "500 Solomon Boulevard",
                            Email = "reader25@library.com",
                            Gender = 1,
                            LocationID = 5,
                            Name = "Reader User25",
                            PhoneNumber = "1111111135",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Library.Models.Book", b =>
                {
                    b.HasOne("Library.Models.Location", "Location")
                        .WithMany("Books")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Library.Models.Loan", b =>
                {
                    b.HasOne("Library.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Models.Location", "Location")
                        .WithMany("Loans")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Library.Models.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.Models.User", b =>
                {
                    b.HasOne("Library.Models.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Library.Models.Location", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Loans");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Library.Models.User", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
